#coding=utf8

mock_gol_search = {
"AdultPaxCount":"1",
"ChildrenPaxCount":"0",
"DepartureStation":"VIX",
"DepartureDate":"2015-05-30",
"ReturnDate":"2015-06-24",
"MaxPrice":"",
"MarketStructure":"RoundTrip",
"ControlGroupSearchView$AvailabilitySearchInputSearchView$DropDownListResidentCountry":"BR",
"bttrechos":"on",
#"ctl00$PlaceHolderCentro$fieldde":"Vitória (VIX)",
"ControlGroupSearchView$AvailabilitySearchInputSearchView$TextBoxMarketOrigin1":"VIX",
#"ctl00$PlaceHolderCentro$fieldpara":"São Paulo - Campinas (VCP)",
"ctl00$PlaceHolderCentro$fieldpara1":"Digite o destino",
"ControlGroupSearchView$AvailabilitySearchInputSearchView$TextBoxMarketDestination1":"VCP",
"ctl00$PlaceHolderCentro$fieldmultide":"Digite a origem",
"ControlGroupSearchView$AvailabilitySearchInputSearchView$TextBoxMarketOrigin2":"",
"ctl00$PlaceHolderCentro$fieldmultipara":"Digite o destino",
"ControlGroupSearchView$AvailabilitySearchInputSearchView$TextBoxMarketDestination2":"",
"data_ida":"30/05/2015",
"ControlGroupSearchView$AvailabilitySearchInputSearchView$DropDownListMarketDay1":"30",
"ControlGroupSearchView$AvailabilitySearchInputSearchView$DropDownListMarketMonth1":"2015-05",
"data_volta":"24/06/2015",
"ControlGroupSearchView$AvailabilitySearchInputSearchView$DropDownListMarketDay2":"24",
"ControlGroupSearchView$AvailabilitySearchInputSearchView$DropDownListMarketMonth2":"2015-06",
"ControlGroupSearchView$AvailabilitySearchInputSearchView$DropDownListPassengerType_ADT":"1",
"ControlGroupSearchView$AvailabilitySearchInputSearchView$DropDownListPassengerType_CHD":"0",
"ControlGroupSearchView$AvailabilitySearchInputSearchView$DropDownListPassengerType_INFT":"0",
"ControlGroupSearchView$AvailabilitySearchInputSearchView$textBoxPromoCode":"",
"ControlGroupSearchView$AvailabilitySearchInputSearchView$RadioButtonMarketStructure":"RoundTrip",
"ControlGroupSearchView$AvailabilitySearchInputSearchView$DropDownListSearchBy":"",
"PageFooter_SearchView$DropDownListOriginCountry":"pt-br",
"ControlGroupSearchView$ButtonSubmit":"compre aqui",
"__EVENTARGUMENT":"",
"__EVENTTARGET":""
}

mock_azul_search = {
"_authkey_":"null",
"ControlGroupSearchView2$AvailabilitySearchInputSearchView2$TextBoxPromoCode":"CALLCENT",
"ControlGroupSearchView2$AvailabilitySearchInputSearchView2$RadioButtonMarketStructure":"RoundTrip",
"__EVENTTARGET":"ControlGroupSearchView2$LinkButtonSubmit",
"ControlGroupSearchView2$AvailabilitySearchInputSearchView2$TextBoxMarketOrigin1":"Vitória (VIX)",
"ControlGroupSearchView2$AvailabilitySearchInputSearchView2$CheckBoxUseMacOrigin1":"",
"ControlGroupSearchView2$AvailabilitySearchInputSearchView2$TextBoxMarketDestination1":"Rio de Janeiro - Santos Dumont (SDU)",
"ControlGroupSearchView2$AvailabilitySearchInputSearchView2$CheckBoxUseMacDestination1":"",
"ControlGroupSearchView2$AvailabilitySearchInputSearchView2$DropDownListMarketDay1":"18",
"ControlGroupSearchView2$AvailabilitySearchInputSearchView2$DropDownListMarketMonth1":"2015-09",
"ControlGroupSearchView2$AvailabilitySearchInputSearchView2$DropDownListMarketDay2":"20",
"ControlGroupSearchView2$AvailabilitySearchInputSearchView2$DropDownListMarketMonth2":"2015-09",
"ControlGroupSearchView2$AvailabilitySearchInputSearchView2$DropDownListPassengerType_ADT":"1",
"ControlGroupSearchView2$AvailabilitySearchInputSearchView2$DropDownListPassengerType_CHD":"0",
"ControlGroupSearchView2$AvailabilitySearchInputSearchView2$DropDownListPassengerType_INFANT":"0",
"ControlGroupSearchView2$AvailabilitySearchInputSearchView2$DropDownListFareTypes":"R"
}